---
title: "Orbital forcing"
author: "Julien Emile-Geay"
date: "6/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(geoChronR)
library(astrochron)
library(ggplot2)
library(ggthemes)
```



```{r astronomical forcing, warning=FALSE, message=FALSE}
L = astrochron::getLaskar()
forc.df = data.frame("t" = L$Time_ka, "prec" = L$prec_LA04, "obl" = L$tilt_LA04, "ecc" = L$ecc_LA04) 
forc1Ma.df = dplyr::filter(forc.df,t<=1000)
#forc.1Ma = reshape2::melt(forc.1Ma,id = 1) # reshape to facilitate on-line plotting call
#ggplot(forc.1Ma) + geom_line(aes(x=t,y=value,colour=variable))
prec = forc1Ma.df[c(1,2)]
prange = c(5,1000)

ggplot(forc1Ma.df) + geom_line(aes(x=t,y=prec), color = "orange") + theme_hc(style = "darkunica") +
  ggtitle("Laskar [2004] precession solution")

spec.mtm <- astrochron::mtm(prec,tbw=3,padfac=5,ar1=TRUE,genplot = F,output=1, verbose = F, detrend=T)  
sig.freq <- astrochron::mtm(prec,tbw=3, padfac=5,ar1=TRUE,genplot = F,output=2, verbose = F, detrend=T)
mtm.df <- data.frame("freq" = spec.mtm$Frequency, "pwr" = spec.mtm$Power)

p.mtm <- plotSpectrum(mtm.df,period_range=prange,period_ticks = pticks, ylims = c(1e-6,5)) + 
  ggtitle("Laskar [2004] precession solution, Multi-taper method, AR(1) null") + xlab("Period (ky)") +
  theme_hc(style = "darkunica") + theme(axis.ticks.x = element_line(color = "gray"))

# label periodicities of interest
#p.mtm <- PeriodAnnotate(p.mtm, periods = c(19,23,41,100))
p.mtm <- PeriodAnnotate(p.mtm, periods = 1/sig.freq$Frequency,colour = "chartreuse",ylims = c(1e-6,1), size = 3)
show(p.mtm)
```
