label.xAxisCalib="Calibrated date";	// title for calibrated date axis
label.xAxisCalend="Calendar date";	// title for calendar date axis
label.xAxisPost="Modelled date";	// title for posterior denstity plot axis
label.xAxisInt="Interval (yrs)";	// title for interval axis
label.yAxisF14C="Radiocarbon determination (F14C)";	// title for radiocarbon axis (F14C)
label.yAxisDelta14C="Delta 14C (per mil)"; // title for permil
label.yAxisBP="Radiocarbon determination (BP)";	// title for radiocarbon axis (BP)
label.yAxisProb="Probability density";	// title for probability axis
label.yAxisPos="Position";		// tile of y axis for depth plots etc
label.axisCalibPrefix="cal";	// prefix for calibrated dates in axes
label.axisCalendPrefix="";		// prefix for calendar dates in axes
label.axisPostPrefix="";		// prefix for modelled dates in axes
label.dateCalendPrefix="";		// prefix for calendar or modelled dates in ranges
label.dateCalibPrefix="cal";	// prefix for calibrated dates in ranges
label.rangeTitleProb="\% probability";	// title of probability ranges
label.rangeTitleSigma=" sigma";	// title of intercept ranges
label.rangeTitlePrefix="  ";	// prefix for each title of the range listing
label.rangePrefix="   ";	// prefix for each line of the range listing
label.rangeUnknown="...";	// shown where one end of the range is unknown
label.sigma="Sigma";		// title for sigma or standard deviation
label.mean="Mean";			// title for mean
label.median="Median";		// title for median
